---
title:  'BSc(Hons) assignment marks'
output: github_document
---

```{r data_input, include = FALSE}
# Packages
library(dplyr)
library(tidyr)
library(readr)

# Assignment 1
assignment_1 <- c('Danielle Beukman' = 10,
                  'Sihle Dakile' = 8,
                  'Carey Hedges' = 6,
                  'Kelly van den Heever' = 10,
                  'Tuwilika Keendjele' = 8,
                  'Ninette Lotter' = 10,
                  'Vishaylan Mahadeo' = 10,
                  'Luyolo Matutu' = 8,
                  'Bongani Mveng' = 6,
                  'Kristen Nel' = 10,
                  'Andani Ratshinanga' = 8,
                  'Carmen Roberts' = 10,
                  'Thando Shabalala' = 10)

# Assignment 2
assignment_2 <- c('Danielle Beukman' = 10,
                  'Sihle Dakile' = 10,
                  'Carey Hedges' = 10,
                  'Kelly van den Heever' = 10,
                  'Tuwilika Keendjele' = 8,
                  'Ninette Lotter' = 10,
                  'Vishaylan Mahadeo' = 10,
                  'Luyolo Matutu' = 10,
                  'Bongani Mveng' = 10,
                  'Kristen Nel' = 10,
                  'Andani Ratshinanga' = 10,
                  'Carmen Roberts' = 10,
                  'Thando Shabalala' = 10)

# Assignment 3
assignment_3 <- c('Danielle Beukman' = 10, # absent
                  'Sihle Dakile' = 9,
                  'Carey Hedges' = 10,
                  'Kelly van den Heever' = 7,
                  'Tuwilika Keendjele' = 10,
                  'Ninette Lotter' = 10,
                  'Vishaylan Mahadeo' = 9,
                  'Luyolo Matutu' = 9,
                  'Bongani Mveng' = 10,
                  'Kristen Nel' = 10,
                  'Andani Ratshinanga' = 9,
                  'Carmen Roberts' = 9,
                  'Thando Shabalala' = 9)

# Assignment 4
assignment_4 <- c('Danielle Beukman' = 10, # absent
                  'Sihle Dakile' = 7,
                  'Carey Hedges' = 9,
                  'Kelly van den Heever' = 9,
                  'Tuwilika Keendjele' = 7,
                  'Ninette Lotter' = 9,
                  'Vishaylan Mahadeo' = 5,
                  'Luyolo Matutu' = 7,
                  'Bongani Mveng' = 9,
                  'Kristen Nel' = 8, # late: -10%
                  'Andani Ratshinanga' = 7,
                  'Carmen Roberts' = 8,
                  'Thando Shabalala' = 9)

# Assignment 5
assignment_5 <- c('Danielle Beukman' = 30, # absent?
                  'Sihle Dakile' = 20,
                  'Carey Hedges' = 25,
                  'Kelly van den Heever' = 27,
                  'Tuwilika Keendjele' = 22,
                  'Ninette Lotter' = 26,
                  'Vishaylan Mahadeo' = 20,
                  'Luyolo Matutu' = 18,
                  'Bongani Mveng' = 26,
                  'Kristen Nel' = 17,
                  'Andani Ratshinanga' = 21,
                  'Carmen Roberts' = 15,
                  'Thando Shabalala' = 20)

# Assignment 6
assignment_6 <- c('Danielle Beukman' = 10, # absent,
                  'Sihle Dakile' = 8,
                  'Carey Hedges' = 10,
                  'Kelly van den Heever' = 8,
                  'Tuwilika Keendjele' = 10,
                  'Ninette Lotter' = 8,
                  'Vishaylan Mahadeo' = 7,
                  'Luyolo Matutu' = 9,
                  'Bongani Mveng' = 10,
                  'Kristen Nel' = 9,
                  'Andani Ratshinanga' = 9,
                  'Carmen Roberts' = 9,
                  'Thando Shabalala' = 10)

# Make dataframe
student_names <- c('Danielle Beukman',
             'Sihle Dakile',
             'Carey Hedges',
             'Kelly van den Heever',
             'Tuwilika Keendjele',
             'Ninette Lotter',
             'Vishaylan Mahadeo',
             'Luyolo Matutu',
             'Bongani Mveng',
             'Kristen Nel',
             'Andani Ratshinanga',
             'Carmen Roberts',
             'Thando Shabalala')

marks_df <- data_frame(Student = student_names,
                       `Exercise.1` = assignment_1,
                       `Exercise.2` = assignment_2,
                       `Exercise.3` = assignment_3,
                       `Exercise.4` = assignment_4,
                       `Exercise.5` = assignment_5,
                       `Exercise.6` = assignment_6)

# Get summary
interim_results <- marks_df %>%
    mutate(`Average.(%)` = 100 * round((`Exercise.1` + `Exercise.2` +
                                        `Exercise.3` + `Exercise.4` +
                                        `Exercise.5` + `Exercise.6`) /
                                            80, 2)) %>%
               arrange(desc(`Average.(%)`))

# Write to csv
write_csv(interim_results, 'assignment_results.csv')
```


```{r tabulation, echo = FALSE, warning = FALSE, message = FALSE}
# Load packages
library(formattable)

# Tabulate
formattable(interim_results, list(
    `Exercise.1` = color_bar('lightblue'),
    `Exercise.2` = color_bar('lightblue'),
    `Exercise.3` = color_bar('lightblue'),
    `Exercise.4` = color_bar('lightblue'),
    `Exercise.5` = color_bar('lightblue'),
    `Exercise.6` = color_bar('lightblue'),
    `Average.(%)` = color_bar('lightgreen')))
```
